const { Visual } = require('../sdk/dist'); // Importing the SDK

async function runDemo() {
    const sdk = new Visual('YOUR_API_KEY');

    // SCENARIO: Testing a temporary Vercel Preview URL against your established "Marketing Site" baselines.

    console.log('🚀 Starting Test...');

    const job = await sdk
        // 1. THE ORIGIN ("Where is the app right now?")
        // This is the dynamic URL generated by your CI (e.g., Vercel, Netlify, Amplify).
        .test('https://marketing-site-git-pr-123.vercel.app')

        // 2. THE PROJECT NAME ("Who is this?")
        // This is CRITICAL. It tells the system:
        // "Even though the URL is weird (pr-123), this is actually the 'Marketing Site'."
        // "Compare these screenshots against the approved 'Marketing Site' baselines."
        .forProject('marketing-site-v2')

        // 3. THE BASELINE (Optional)
        // If the 'Marketing Site' project has no baselines yet, 
        // use this URL to generate them on the fly.
        .against('https://www.example.com')

        // 4. AUTO-DISCOVERY (Optional)
        // Crawl sitemap.xml and add pages matching '/blog/**'
        // but ignore drafts.
        .scan('/blog/**', { exclude: ['/blog/drafts/**'] })

        .on(['Desktop Chrome', 'iPhone 12'])
        .run();

    console.log(`Job Started: ${job.jobId}`);
    
    // The system now knows:
    // - Take screenshots of 'marketing-site-git-pr-123...'
    // - Load "Golden Master" images from project 'marketing-site-v2'
    // - Compare them.
}

runDemo();
