const { RegressionBot } = require('regressionbot'); // Using the package name

async function runDemo() {
    // We recommend using the REGRESSIONBOT_API_KEY environment variable,
    // but you can also pass it explicitly to the constructor.
    const sdk = new RegressionBot(process.env.REGRESSIONBOT_API_KEY || 'YOUR_API_KEY');

    // SCENARIO: Testing a dynamic Preview URL against your production "Marketing Site" baselines.

    console.log('🚀 Starting Visual Test...');

    const job = await sdk
        // 1. THE CANDIDATE (Test Origin)
        // This is the dynamic URL generated by your CI (e.g., Vercel, Netlify, Amplify).
        .test('https://marketing-site-git-pr-123.vercel.app')

        // 2. THE PROJECT ("Who is this?")
        // This is CRITICAL. It tells RegressionBot:
        // "Even though the URL is dynamic (pr-123), this is actually the 'Marketing Site' project."
        // "Compare these screenshots against the approved 'Marketing Site' baselines."
        .forProject('marketing-site-prod')

        // 3. THE BASELINE (Optional)
        // If the project doesn't have baselines yet, or you want to compare 
        // two live URLs directly (Preview vs Production), set the baseline here.
        .against('https://www.regressionbot.com')

        // 4. AUTO-DISCOVERY (Optional)
        // Crawl the sitemap and add pages matching '/docs/**'
        .scan('/docs/**', { limit: 10 })

        // 5. MATRIX (Devices)
        // Test on both Desktop and Mobile viewports.
        .on(['Desktop Chrome', 'iPhone 13'])
        
        // 6. EXECUTE
        // Compiles the manifest and triggers the API.
        .run();

    console.log(`Job triggered successfully! Job ID: ${job.jobId}`);
    
    // Wait for the job to complete (usually 30-60 seconds depending on site size)
    console.log('Waiting for results...');
    const result = await job.waitForCompletion();
    
    // Get detailed summary
    const summary = await job.getSummary();
    
    if (result.overallScore < 100) {
        console.log(`⚠️ Visual regressions detected! Stability Score: ${result.overallScore}/100`);
        console.log(`Regressions: ${summary.regressionCount}`);
        if (summary.collageUrl) {
            console.log(`Collage: ${summary.collageUrl}`);
        }
    } else {
        console.log('✅ No visual changes detected. Site is stable!');
    }
}

runDemo().catch(err => {
    console.error('Error running visual test:', err);
    process.exit(1);
});
