export interface ProjectPath {
    path: string;
    label?: string;
}

export interface ProjectScan {
    pattern: string;
    options?: {
        limit?: number;
        exclude?: string[];
    };
}

export interface ProjectConfig {
    orgId?: string;
    name: string;
    testOrigin?: string;
    baseOrigin?: string;
    sitemapUrl?: string;
    paths?: ProjectPath[];
    scans?: ProjectScan[];
    devices?: string[];
    masks?: string[];
    concurrency?: number;
    createdAt?: string;
    updatedAt?: string;
    lastRunAt?: string;
    lastJobId?: string;
    baselineInvalidatedAt?: string;
}

export interface VRConfig {
    apiKey?: string;
    apiUrl?: string;
}

export interface Viewport {
    width: number;
    height: number;
}

export const Viewports = {
    DESKTOP: { width: 1920, height: 1080 },
    LAPTOP: { width: 1366, height: 768 },
    TABLET: { width: 768, height: 1024 },
    MOBILE: { width: 375, height: 667 }
} as const;

/**
 * Result for a single URL + device comparison.
 *
 * Returned by both getStatus() and getSummary(). Pre-signed image URLs
 * (baselineUrl, currentUrl, diffUrl) are only populated by getSummary() —
 * they are absent when reading results from getStatus().
 */
export interface PageResult {
    url: string;
    /** Device variant tested (e.g. "desktop_chrome", "iphone_12"). */
    variantName: string;
    /** Percentage of pixels that differed from the baseline (0 = identical). */
    diffPercentage: number;
    /** Raw count of differing pixels. */
    diffCount: number;
    /** Perceptual similarity 0-100 (SSIM). */
    visualMatchScore: number;
    /** Plain-English description of what visually changed, generated by RegressionBot. */
    regressionbotSummary?: string;
    /** Pre-signed URL for the stored baseline screenshot. */
    baselineUrl?: string;
    /** Pre-signed URL for the newly captured screenshot. */
    currentUrl?: string;
    /** Pre-signed URL for the side-by-side annotated diff image. */
    diffUrl?: string;
}

export interface JobProgress {
    total: number;
    completed: number;
    percent: string;
}

export interface JobStatus {
    jobId: string;
    status: 'INITIALIZING' | 'PROCESSING' | 'FINISHING' | 'SUMMARIZING' | 'COMPLETED' | 'APPROVED' | 'FAILED';
    summaryStatus?: 'PENDING' | 'PROCESSING' | 'COMPLETE' | 'NONE';
    error?: string;
    progress?: JobProgress;
    executionTime?: number;
    createdAt?: string;
    /** Partial or complete results. Present once workers start completing. Pre-signed image URLs are not included — call getSummary() for those. */
    results?: PageResult[];
}

export interface JobSummary {
    jobId: string;
    status: string;
    summaryStatus?: 'PENDING' | 'PROCESSING' | 'COMPLETE' | 'NONE';
    error?: string | null;
    totalUrls: number;
    completedCount: number;
    /** Overall quality score 0–100 across all tested pages. */
    overallScore: number;
    executionTime: number;
    regressionCount: number;
    matchCount: number;
    newBaselineCount: number;
    errorCount: number;
    /** Pages where a visual regression was detected. Includes pre-signed image URLs. */
    regressions: PageResult[];
    /** Pages that matched the baseline. Includes pre-signed image URLs. */
    matches: PageResult[];
    /** Pages captured for the first time — no baseline existed to compare against. */
    newBaselines: Array<{ url: string; variantName: string }>;
    /** Pages that failed to capture or compare. */
    errors: Array<{ url: string; variantName: string; errorMessage: string }>;
}

export interface JobAiSummary {
    message: string;
    jobId: string;
    summaries: Array<{
        url: string;
        variantName: string;
        regressionbotSummary: string;
    }>;
}

export interface JobCollage {
    jobId: string;
    collageKey: string;
    collageUrl: string;
    regressionCount: number;
}
